#+title: jtx1inst

A custom C API for instrumenting Jetson TX1's SoM and SoC with the use of userspace I2C and sysfs files. This is small C library for accessing two Jetson TX1's INA3221 -- current and voltage monitors as well as on-module temperature sensors and other information such as GPU, CPUs and EMC operating frequencies -- either through sysf nodes or userspace I2C. The current version has been tested on the Jetson TX1 module with a SKU =699-82180-1000-100= obtained with =i2cdump -y -r 0x14-0x26 2 0x50 b= command. 

* Build and install

In order to build and install the library and sample programs use the following commands.

#+begin_src sh
mkdir build
cd build
cmake ..
make
sudo make install
sudo ldconfig
#+end_src

* Documentation

In order to generate documentation from sources annotated with Doxygen use the following command in [[./doc][doc]] directory.

#+begin_src sh
doxygen config
#+end_src


* License

This is free and unencumbered software released into the public domain. For more information, please refer to the [[./LICENSE][LICENSE]] file.
